# Importing numpy library

In [1]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

# Numerical Operations 

In [2]:
np.sqrt(20) #Square Root

4.47213595499958

In [4]:
np.power(4,2) #Power

16

In [5]:
np.exp(3)

20.085536923187668

In [6]:
np.sin(3)

0.1411200080598672

In [7]:
np.cos(3)

-0.9899924966004454

In [8]:
np.tan(3)

-0.1425465430742778

In [9]:
np.log(5)

1.6094379124341003

In [10]:
np.log10(5)

0.6989700043360189

In [11]:
np.log2(4)

2.0

In [12]:
np.round(10.3456)

10.0

In [13]:
np.round(10.3456, 2)

10.35

# Special numpy values

In [14]:
np.pi

3.141592653589793

In [15]:
np.e

2.718281828459045

In [16]:
np.inf          # infinily

inf

In [17]:
np.NINF         # negative infinity

-inf

In [18]:
-np.inf

-inf

# Creating numpy arrays

# One dimensional arrays

In [19]:
L=[23,33,35,56,67,78]
arr=np.array(L)
print(arr)

[23 33 35 56 67 78]


In [20]:
arr

array([23, 33, 35, 56, 67, 78])

# Two dimensional arrays

In [21]:
L=[[12,22,23],[56,54,77]]
arr=np.array(L)
print(arr)

[[12 22 23]
 [56 54 77]]


In [22]:
arr

array([[12, 22, 23],
       [56, 54, 77]])

# Array properties

In [23]:
arr1=np.array([23,33,35,56,67,78])
arr2=np.array([[12,22,23],[56,54,77]])

In [24]:
arr1

array([23, 33, 35, 56, 67, 78])

In [25]:
arr2

array([[12, 22, 23],
       [56, 54, 77]])

# Shape of the array

In [26]:
print(arr1.shape)
print(arr2.shape)

(6,)
(2, 3)


# Reshape of the array

In [46]:
L = [2, 5, 3, 9, 4, 7, 5, 6, 8, 2, 5, 3, 9, 4, 7, 5, 6, 8]

np.reshape(L,(2, 9))

array([[2, 5, 3, 9, 4, 7, 5, 6, 8],
       [2, 5, 3, 9, 4, 7, 5, 6, 8]])

In [53]:
L = np.array(L)

L.reshape(6, 3)

array([[2, 5, 3],
       [9, 4, 7],
       [5, 6, 8],
       [2, 5, 3],
       [9, 4, 7],
       [5, 6, 8]])

In [51]:
L = np.array(L)

L.shape = (3, 6)
L

array([[2, 5, 3, 9, 4, 7],
       [5, 6, 8, 2, 5, 3],
       [9, 4, 7, 5, 6, 8]])

# Dimensions of the array

In [27]:
print(arr1.ndim)
print(arr2.ndim)

1
2


# Data type inside arrays

In [28]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


# Size of arrays

In [29]:
print(arr1.size)
print(arr2.size)

6
6


# Special arrays

# Null array

In [36]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Ones array

In [38]:
a=np.ones(20)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [39]:
b=np.ones((5,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Identity matrix

In [40]:
I3=np.eye(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Simulating random integers

In [41]:
r=np.random.randint(2,8)      # One random integer from 2 to 8

In [42]:
r

2

In [43]:
r=np.random.randint(2,8,10)      # 10 random integers from 2 to 8

In [44]:
r

array([5, 7, 2, 4, 6, 5, 6, 7, 3, 6])

In [58]:
r=np.random.randint(2,8,10).reshape(5, 2)   
r

array([[5, 7],
       [3, 7],
       [2, 7],
       [4, 5],
       [6, 5]])

# Simulating random floats from 0 to 1

In [54]:
r=np.random.random(5)

In [55]:
r

array([0.06186916, 0.70372751, 0.28269965, 0.23539384, 0.50892852])

In [56]:
r=np.random.random((5,5))

In [57]:
r

array([[0.57351724, 0.25505404, 0.7798147 , 0.14238607, 0.74899875],
       [0.24209325, 0.98489917, 0.06662366, 0.46052059, 0.80730653],
       [0.93213691, 0.01850696, 0.54974196, 0.61525588, 0.69191681],
       [0.46958334, 0.27964928, 0.79343988, 0.37790783, 0.86615302],
       [0.69043811, 0.17156683, 0.01913784, 0.78506106, 0.25200809]])

# Simulating random floats in any range

In [59]:
r=np.random.uniform(1,5)

In [60]:
r

1.5336699562507556

In [61]:
r=np.random.uniform(1,5,10)

In [62]:
r

array([3.56660531, 3.75190145, 2.862366  , 1.09417229, 4.14807476,
       4.03445394, 1.20795189, 3.79924242, 3.23664744, 2.23929309])

# Generating sequence

# arange function with single dimension

In [63]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr=np.arange(3,10)

In [65]:
arr

array([3, 4, 5, 6, 7, 8, 9])

# Changing the shape of the sequence array

In [66]:
arr=np.arange(20)
arr.shape=(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Creating Vectors

In [68]:
arr=np.array([12,23,34,43,44,45,56,32,33,56])
arr.shape=(10,1)
arr

array([[12],
       [23],
       [34],
       [43],
       [44],
       [45],
       [56],
       [32],
       [33],
       [56]])

In [69]:
arr=np.array([12,23,34,43,44,45,56,32,33,56]).reshape(10,1)
arr

array([[12],
       [23],
       [34],
       [43],
       [44],
       [45],
       [56],
       [32],
       [33],
       [56]])

# Indexing & slicing one dimensional numpy arrays

In [70]:
a=np.array([12,22,34,56,54,56])

In [71]:
a[0]

12

In [72]:
a[2]

34

In [73]:
a[-1]

56

In [74]:
a[2:5]

array([34, 56, 54])

In [75]:
a[3:]

array([56, 54, 56])

In [76]:
a[:3]

array([12, 22, 34])

In [77]:
a[::2]

array([12, 34, 54])

In [78]:
a[::-1]

array([56, 54, 56, 34, 22, 12])

# Indexing & slicing multi dimensional numpy arrays

In [85]:
b=np.array([[23,33,34,45,56],[23,33,34,56,54],[78,65,67,64,78]])
b

array([[23, 33, 34, 45, 56],
       [23, 33, 34, 56, 54],
       [78, 65, 67, 64, 78]])

In [86]:
b[0,3]

45

In [87]:
b[:2,1:4]

array([[33, 34, 45],
       [33, 34, 56]])

In [88]:
b[1,[2,4]]

array([34, 54])

# Numpy arrays are mutable

In [178]:
a = np.array([12, 45, 23, 11, 25, 91, 23, 56, 23, 19, 78, 66])

In [179]:
a[0]=100

In [180]:
a

array([100,  45,  23,  11,  25,  91,  23,  56,  23,  19,  78,  66])

In [181]:
a[4:7] = [2, 9, 5]
a

array([100,  45,  23,  11,   2,   9,   5,  56,  23,  19,  78,  66])

In [183]:
a = np.array([[12, 45, 23, 11], [25, 91, 23, 56], [23, 19, 78, 66], [15, 81, 23, 56], [25, 91, 73, 16]])

a[1:4, 1:3] =  np.random.randint(1, 12, 6).reshape(3, 2)
a

array([[12, 45, 23, 11],
       [25, 10,  1, 56],
       [23,  5,  3, 66],
       [15,  6,  6, 56],
       [25, 91, 73, 16]])

# mathematical operation

In [186]:
a = np.array([1, 6, 9, 5, 3, 5, 7])
a

array([1, 6, 9, 5, 3, 5, 7])

In [187]:
a+5

array([ 6, 11, 14, 10,  8, 10, 12])

In [102]:
a*a

array([1156, 2025, 1089,  529, 2025, 4489, 4225, 6084,  441])

In [188]:
a>5

array([False,  True,  True, False, False, False,  True])

# Array masking

In [189]:
a = np.array([1, 6, 9, 5, 3, 5, 7])
a

array([1, 6, 9, 5, 3, 5, 7])

In [190]:
a>50

array([False, False, False, False, False, False, False])

In [191]:
a[a>50]

array([], dtype=int32)

In [192]:
a[[False, True, True, False, False, False, True]]

array([6, 9, 7])

# Replacing existing values with new values

In [194]:
a=np.array([-23,34,-15,-22,56])

In [195]:
np.where(a>0)

(array([1, 4], dtype=int64),)

In [196]:
b=np.where(a>0,a,0)

In [197]:
b

array([ 0, 34,  0,  0, 56])

In [199]:
d=np.where(a>0,"x","y")
d

array(['y', 'x', 'y', 'y', 'x'], dtype='<U1')

In [200]:
a = np.array([71, 46, 59, 35, 83, 45, 17, 91, 88, 36, 65])

np.where(a>50, "Pass", "Fail")

array(['Pass', 'Fail', 'Pass', 'Fail', 'Pass', 'Fail', 'Fail', 'Pass',
       'Pass', 'Fail', 'Pass'], dtype='<U4')

# numpy functions with arrays

In [116]:
arr=np.array([34,33,21,25,56,32,44,78,12])

In [117]:
arr.min()

12

In [118]:
arr.max()

78

In [119]:
arr.mean()

37.22222222222222

In [120]:
arr.sort()
arr

array([12, 21, 25, 32, 33, 34, 44, 56, 78])

In [121]:
np.median(arr)

33.0

# Stacking numpy arrays

# Vertical stacking & horizontal stacking

In [122]:
a=np.array([[3,4,5],[6,3,5]])
b=np.array([[2,3,7],[8,2,6]])

In [123]:
c=np.vstack((a,b))
print(c)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


In [124]:
d=np.hstack((a,b))
print(d)

[[3 4 5 2 3 7]
 [6 3 5 8 2 6]]


# Appending

In [125]:
a=np.array([[3,4,5],[6,3,5]])
b=np.array([[2,3,7],[8,2,6]])

In [126]:
c=np.append(a,b,axis=0)
print(c)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


In [127]:
d=np.append(a,b,axis=1)
print(d)

[[3 4 5 2 3 7]
 [6 3 5 8 2 6]]


# Concatenation

In [128]:
a=np.array([[3,4,5],[6,3,5]])
b=np.array([[2,3,7],[8,2,6]])

In [129]:
c=np.concatenate((a,b),axis=0)
print(c)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


In [130]:
d=np.concatenate((a,b),axis=0)
print(d)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


# Tiling

In [131]:
a=np.array([23,34])
b=np.tile(a,(1,2))
print(b)

[[23 34 23 34]]


In [132]:
a=np.array([23,34])
b=np.tile(a,(2,2))
print(b)

[[23 34 23 34]
 [23 34 23 34]]


In [133]:
a=np.array([[23,34],[56,54]])
b=np.tile(a,(1,2))
print(b)

[[23 34 23 34]
 [56 54 56 54]]


# Splitting arrays

# Horizontal splitting

In [134]:
a=np.random.random((4,4))
a

array([[0.67213012, 0.18340301, 0.49430999, 0.1569766 ],
       [0.50710688, 0.50533182, 0.9847469 , 0.01758845],
       [0.21626384, 0.3857311 , 0.33227086, 0.21435769],
       [0.91390626, 0.31799399, 0.40432337, 0.82255262]])

In [135]:
b=np.hsplit(a,2)
b

[array([[0.67213012, 0.18340301],
        [0.50710688, 0.50533182],
        [0.21626384, 0.3857311 ],
        [0.91390626, 0.31799399]]),
 array([[0.49430999, 0.1569766 ],
        [0.9847469 , 0.01758845],
        [0.33227086, 0.21435769],
        [0.40432337, 0.82255262]])]

In [140]:
b=np.hsplit(a,4)
b[2]

array([[0.49430999],
       [0.9847469 ],
       [0.33227086],
       [0.40432337]])

# Vertical spliiting

In [141]:
a=np.random.random((4,4))
a

array([[0.4852618 , 0.73502073, 0.56610766, 0.3002754 ],
       [0.52193487, 0.35856383, 0.87416811, 0.07898078],
       [0.05478744, 0.67515334, 0.89212181, 0.01871931],
       [0.16317621, 0.44831874, 0.86580057, 0.21545207]])

In [142]:
b=np.vsplit(a,2)
b

[array([[0.4852618 , 0.73502073, 0.56610766, 0.3002754 ],
        [0.52193487, 0.35856383, 0.87416811, 0.07898078]]),
 array([[0.05478744, 0.67515334, 0.89212181, 0.01871931],
        [0.16317621, 0.44831874, 0.86580057, 0.21545207]])]

# Rolling array elements

In [143]:
arr=np.array([1,2,3,4])
np.roll(arr,1)

array([4, 1, 2, 3])

In [144]:
arr=np.array([1,2,3,4])
np.roll(arr,2)

array([3, 4, 1, 2])

In [145]:
arr=np.array([1,2,3,4])
np.roll(arr,-1)

array([2, 3, 4, 1])

# Changing the data type

In [146]:
a=np.array([12.34,23.46,32.56])
b=a.astype(int)
b

array([12, 23, 32])

In [147]:
a=np.array(["12.34","23.46","32.56"])
b=a.astype(float)
b

array([12.34, 23.46, 32.56])

In [ ]:
'''
i - integer
b - boolean
u - unfile integer
f - float
c - complerx float
m - time date
M - date time
O - object(string)
S - string
U - unicode string
'''

In [201]:
a = np.array([2, 6, 5])

a.dtype

dtype('int32')

In [202]:
a = np.array([2, 6, 5], dtype = "O")
print(a)
a.dtype

[2 6 5]


dtype('O')

In [203]:
a = np.array([2, 6, 5], dtype = "S")
print(a)
a.dtype

[b'2' b'6' b'5']


dtype('S1')

# Matrix operations

# Scaler multiplication

In [148]:
m1=np.array([[12,22,23],[45,43,33]])
3*m1

array([[ 36,  66,  69],
       [135, 129,  99]])

# Matrix addition & substraction

In [149]:
m1=np.array([10,20,30,40])
m2=np.array([30,40,50,60])

In [150]:
m1+m2

array([ 40,  60,  80, 100])

In [151]:
m1-m2

array([-20, -20, -20, -20])

In [152]:
m1=np.array([[12,22,23],[45,43,33]])
m2=np.array([[22,21,43],[46,23,13]])

In [153]:
m1+m2

array([[34, 43, 66],
       [91, 66, 46]])

In [154]:
m1-m2

array([[-10,   1, -20],
       [ -1,  20,  20]])

# Broadcasting

In [155]:
m1=np.array([10,20,30,40])

In [156]:
m1=m1+100
m1

array([110, 120, 130, 140])

# Matrix multiplication

In [157]:
m1=np.array([[12,23],[10,25]])
m2=np.array([[10,15],[5,15]])

In [159]:
m1*m2         # Hadamard product

array([[120, 345],
       [ 50, 375]])

In [160]:
np.dot(m1,m2)

array([[235, 525],
       [225, 525]])

In [161]:
m1.dot(m2)

array([[235, 525],
       [225, 525]])

In [162]:
np.dot(m2,m1)

array([[270, 605],
       [210, 490]])

In [163]:
m2.dot(m1)

array([[270, 605],
       [210, 490]])

# Trace of a matrix

In [165]:
m1=np.array([[12,23],[10,25]])

In [166]:
np.trace(m1)

37

# Diagonal elements of a square matrix

In [167]:
m1=np.array([[12,23],[10,25]])

In [168]:
np.diag(m1)

array([12, 25])

# Matrix transpose

In [169]:
m1=np.array([[12,23],[10,25]])
np.transpose(m1)

array([[12, 10],
       [23, 25]])

# Flipping

In [170]:
m1=np.array([[12,23],[10,25]])
m1

array([[12, 23],
       [10, 25]])

In [171]:
np.flip(m1)

array([[25, 10],
       [23, 12]])

In [172]:
np.fliplr(m1)

array([[23, 12],
       [25, 10]])

In [173]:
np.flipud(m1)

array([[10, 25],
       [12, 23]])